DROP INDEX IF EXISTS adapter_version_reviews_tenant_version_idx;
DROP TABLE IF EXISTS adapter_version_reviews;
DROP INDEX IF EXISTS adapter_test_vectors_tenant_version_idx;
DROP TABLE IF EXISTS adapter_test_vectors;
DROP INDEX IF EXISTS adapter_versions_scope_name_state_idx;
DROP INDEX IF EXISTS adapter_versions_scope_name_version_idx;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS retired_at;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS deprecated_at;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS activated_at;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS reviewed_at;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS activated_by;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS reviewed_by;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS created_by;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS review_notes;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS test_results_json;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS risk_level;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS provenance_url;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS sbom_sha256;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS package_signature;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS package_sha256;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS definition_sha256;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS definition_json;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS kind;
ALTER TABLE adapter_versions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE adapter_versions ADD CONSTRAINT adapter_versions_name_version_key UNIQUE (name, version);
DROP INDEX IF EXISTS provider_adapters_tenant_state_idx;
DROP INDEX IF EXISTS provider_adapters_scope_name_idx;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS retired_at;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS updated_at;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS created_by;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS provenance_url;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS risk_level;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS description;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS kind;
ALTER TABLE provider_adapters DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE provider_adapters ADD CONSTRAINT provider_adapters_name_key UNIQUE (name);
