apiVersion: v1
kind: ConfigMap
metadata:
  name: webhookery-config
  namespace: webhookery
  labels:
    app.kubernetes.io/name: webhookery
data:
  WEBHOOKERY_HTTP_ADDR: ":8080"
  WEBHOOKERY_ENABLE_UI: "false"
  WEBHOOKERY_ENVIRONMENT: "production"
  WEBHOOKERY_RAW_STORAGE_MODE: "postgres"
  WEBHOOKERY_OBJECT_STORAGE_USE_SSL: "true"
